# Generated by Django 5.0 on 2024-01-08 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('username_one', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_username_one', to=settings.AUTH_USER_MODEL)),
                ('username_two', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_username_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('username_two', 'username_one')},
            },
        ),
    ]
