# Generated by Django 5.0 on 2024-01-12 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_messagemodel_chat_name_groupchatmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToAddGroupChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_request_add_to_group_chat', to=settings.AUTH_USER_MODEL)),
                ('group_chat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chats_name', to='chat.groupchatmodel')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_request_add_to_group_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group_chat_name', 'to_user')},
            },
        ),
    ]
