# Generated by Django 5.0 on 2024-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_requesttoaddgroupchatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmodel',
            name='name',
            field=models.CharField(default=2023, max_length=33),
            preserve_default=False,
        ),
    ]
