# Generated by Django 5.0 on 2024-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupchatmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/static/images/%Y/%M/%D'),
        ),
    ]
