# Generated by Django 5.0 on 2024-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_usermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Фамилия'),
        ),
    ]
