# Generated by Django 5.0 on 2024-02-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_usermodel_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание профиля'),
        ),
    ]
